services:
  - type: web
    name: photo-booth-ai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: OPENAI_API_KEY
        fromEnvVar: OPENAI_API_KEY
